apiVersion: v1
kind: Service
metadata:
  name: backenddos-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: server
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 31516