apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakcenddos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec: 
      containers:
        - name: backenddos
          image: nodlez/backend_dos:v1
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 3001