apiVersion: v1
kind: Service
metadata:
  name: backenduno-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30100