apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenduno-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec: 
      containers:
        - name: backenduno
          image: nodlez/backend_uno:v1
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 3002