apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenduno-deployment
spec:
  selector:
    matchLabels:
      app: backenduno
  replicas: 1
  template:
    metadata:
      labels:
        app: backenduno
    spec:
      containers:
      - name: backenduno
        image: nodlez/backend_uno:v1
        ports:
          - containerPort: 3002